name: Timie
description: Control your mobile screen time

dependencies:
  flutter:
    sdk: flutter
  android_alarm_manager: 0.3.0
  google_sign_in: 4.0.0
  firebase_analytics: 2.0.0
  firebase_auth: ^0.8.0+1
  firebase_database: 2.0.0
  firebase_storage: 2.0.0
  intl: 0.15.7

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

  usage_stats:
    path: ../usage_stats

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true